server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
#         uri: file://${user.home}/config-repo
          uri: http://192.168.13.199/docs/config-repo.git
          search-paths: didispace,itscore,msg_dispatcher
          username: xugr
          password: ZNiTdeH1
          force-pull: true
        health:
          repositories:
            check:
              #应用名
              name: check-repo
              #分支名
              label: master
              #环境名
              profile: default
        prefix:
  application:
    name: config-server
#添加用户名/密码访问
security:
  user:
    name: user
    password: userPwd
encrypt:
  key-store:
    location: classpath:server.jks
    password: testtest
    alias: mykey
eureka:
  client:
    service-url:
      defaultZone: http://192.168.11.202:1111/eureka/