server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: http://192.168.13.199
          search-paths: docs/config-repo
          username: test
          password: test
  application:
    name: config-server