server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
#         uri: file://${user.home}/config-repo
          uri: http://192.168.13.199/docs/config-repo.git
          search-paths: didispace,itscore,msg_dispatcher
          username: test
          password: test
          force-pull: true
        health:
          repositories:
            check:
              #应用名
              name: check-repo
              #分支名
              label: master
              #环境名
              profile: default
  application:
    name: config-server
#添加用户名/密码访问
security:
  user:
    name: user
    password: userPwd