server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: git@192.168.13.199:docs/config-repo.git
          search-paths: didispace
          username: test
          password: test
  application:
    name: config-server